### ISSUE TITLE
errors.new("error") prints error message ":error"

### ISSUE THREAD

**Issue by saumanbiswas** [appscode/errors#4]

**Comment by sadlil** [comment]
Can you please provide more information. Better if you give a code snippets and associated output.

**Comment by saumanbiswas** [comment]
func main() {
	fmt.Println(errors.New("test"))
}

output : 
:test
a colon comes in front of the message. Should it be there ???

**Comment by sadlil** [comment]
errors should not be used like this. It must follow the pattern as
```
errors.New()
          .WithMessage()  // If you have extra message
          .WithCause()      // if you have underlying go error
          .WithContext()    // if you have context
          .Internal() / .NotFound() // This Is build. Those method Must be Called at last it returns an error 
```
